version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - bazadb:/var/lib/postgresql/data

volumes:
  bazadb:
